### ISSUE TITLE
Customize text selection color

### ISSUE THREAD

**Issue by chrismlusk** [chrismlusk/accuraty-templates#62]
Add something like this to `_base.scss`:

```scss
::selection {
  background-color: rgba($primary, 0.25);
}
```
